# Generated by Django 5.1.2 on 2024-11-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='accounts.company'),
        ),
        migrations.CreateModel(
            name='CompanyAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_url', models.TextField()),
                ('meta_token', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('phone_number_id', models.CharField(max_length=255)),
                ('business_id', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_authentication', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('tax_clearance', models.ImageField(upload_to='tax_clearance/')),
                ('bank_statement', models.ImageField(upload_to='bank_statement/')),
                ('cert_of_incorporation', models.ImageField(upload_to='cert_of_incorporation/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='accounts.company')),
            ],
        ),
    ]
