# Generated by Django 5.1.2 on 2024-11-22 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_account_company_companyauthentication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='accounts.company'),
            preserve_default=False,
        ),
    ]
