# Generated by Django 5.1.2 on 2024-11-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_status_chatroom_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='latest_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_message_chatrooms', to='chat.message'),
        ),
    ]
