# Generated by Django 5.1.2 on 2024-11-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_account_company_companyauthentication_and_more'),
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='accounts.company')),
            ],
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
