# Generated by Django 5.1.2 on 2024-11-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_companybalance_delete_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('top_up', 'Credit'), ('deduction', 'Debit')], max_length=10),
        ),
    ]
