# Generated by Django 5.1.2 on 2024-11-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='invoice_file',
        ),
        migrations.AddField(
            model_name='income',
            name='income_slip',
            field=models.FileField(blank=True, null=True, upload_to='income/'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
