# Generated by Django 5.1.2 on 2024-12-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_expenserequest_uuid_income_uuid_invoice_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
