# Generated by Django 5.1.2 on 2024-12-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_expenserequest_date_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
    ]
