# Generated by Django 5.1.2 on 2024-12-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_expenserequest_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='selected',
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
