# Generated by Django 5.1.2 on 2024-11-21 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_response_text'),
        ('chat', '0004_chatroom_latest_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='menu', max_length=255)),
                ('position', models.CharField(default='menu', max_length=255)),
                ('previous_menu', models.CharField(default='menu', max_length=255)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('stamp', models.CharField(default='menu', max_length=255)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.client')),
            ],
        ),
    ]
